version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env.example
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_BASE_URL=http://backend:8000
    depends_on:
      - backend

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uv run celery -A app.main worker --loglevel=info
    env_file:
      - backend/.env.example
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: time_track
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata:
